# Configures the version of the dependencies of various generated packages, and
# related information.

auth:
  python:
    version: '1.4.11'
  ruby:
    version: '0.4.1'

grpc:
  core:
    version: '0.9.0'
  objc:
    version: '0.5.0'
    ios:
      deployment_target: '6.0'
    osx:
      deployment_target: '10.8'
  python:
    version: '0.9.0a0'
  ruby:
    version: '0.9.3'

protobuf:
  version: '3.0.0-alpha-3'
